libarary(base)
libarary(cast)
libarary(curl)
libarary(cast)
libarary(Hmisc)
libarary(plyr)
libarary(dplyr)
libarary(data.table)
libarary(httr)
libarary(knitr)
libarary(magrittr)
packaes(reshape2)
libarary(utils)

